server:
  port: 10010
spring:
  application:
    name: agent-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: localhost
zuul:
  prefix: /api
  routes:
    traveller-service:
      path: /identity/**
      serviceId: agent-identity-service
      strip-prefix: false
    activity-service:
      path: /activity/**
      serviceId: agent-activity-service
      strip-prefix: false
    service-service:
      path: /service/**
      serviceId: agent-service-service
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillieseconds: 205000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000